apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /
    prometheus.io/port:   '8780'
spec:
  selector:
    app: jenkins-server
  ports:
    - port: 8780
      targetPort: 8780
      nodePort: 31100
  type: NodePort