apiVersion: v1
kind: Service
metadata:
  name: microservices-users
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081