apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
spec:
  destination:
    name: ''
    namespace: microservices
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s
    repoURL: 'https://github.com/azizzakiryarov/microservices-users-gitops.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
